
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
create_clock -period 100.000 -name jtag_tck -waveform {0.000 50.000} -add [get_ports JTAG_tck]

create_clock -period 100.000 -name mdc_clk -waveform {0.000 50.000} -add [get_ports mdc]
create_clock -period 40.000 -name mrx_clk -waveform {0.000 20.000} -add [get_ports MII_rx_clk]
create_clock -period 40.000 -name mtx_clk -waveform {0.000 20.000} -add [get_ports MII_tx_clk]

set_clock_groups -name rocketMac -asynchronous -group [get_clocks {clkout clk}] -group jtag_tck -group mdc_clk -group mrx_clk -group mtx_clk



#####               MCU JTAG define           #####

set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports UART_txd]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports UART_rxd]


set_property PACKAGE_PIN D9 [get_ports {GPIO2_0_tri_i[0]}]
set_property PACKAGE_PIN C9 [get_ports {GPIO2_0_tri_i[1]}]
set_property PACKAGE_PIN B9 [get_ports {GPIO2_0_tri_i[2]}]
set_property PACKAGE_PIN B8 [get_ports {GPIO2_0_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO2_0_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO2_0_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO2_0_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO2_0_tri_i[0]}]
set_property PACKAGE_PIN E2 [get_ports JTAG_tck]
set_property PACKAGE_PIN D2 [get_ports JTAG_td_i]
set_property PACKAGE_PIN H2 [get_ports JTAG_td_o]
set_property PACKAGE_PIN G2 [get_ports JTAG_tms]
set_property IOSTANDARD LVCMOS33 [get_ports JTAG_tck]
set_property IOSTANDARD LVCMOS33 [get_ports JTAG_td_i]
set_property IOSTANDARD LVCMOS33 [get_ports JTAG_td_o]
set_property IOSTANDARD LVCMOS33 [get_ports JTAG_tms]
set_property PACKAGE_PIN D18 [get_ports {MII_rxd[0]}]
set_property PACKAGE_PIN E17 [get_ports {MII_rxd[1]}]
set_property PACKAGE_PIN E18 [get_ports {MII_rxd[2]}]
set_property PACKAGE_PIN G17 [get_ports {MII_rxd[3]}]
set_property PACKAGE_PIN F15 [get_ports MII_rx_clk]
set_property PACKAGE_PIN G16 [get_ports MII_rx_dv]
set_property PACKAGE_PIN C17 [get_ports MII_rx_er]
set_property PACKAGE_PIN H16 [get_ports MII_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {MII_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MII_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MII_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MII_rxd[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports MII_col]
#set_property IOSTANDARD LVCMOS33 [get_ports MII_crs]
set_property IOSTANDARD LVCMOS33 [get_ports MII_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports MII_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports MII_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports MII_tx_clk]
set_property PACKAGE_PIN C2 [get_ports ext_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset]
set_property PACKAGE_PIN E1 [get_ports {GPIO_0_tri_o[0]}]
set_property PACKAGE_PIN G6 [get_ports {GPIO_0_tri_o[1]}]
set_property PACKAGE_PIN F6 [get_ports {GPIO_0_tri_o[2]}]
set_property PACKAGE_PIN G4 [get_ports {GPIO_0_tri_o[3]}]
set_property PACKAGE_PIN G3 [get_ports {GPIO_0_tri_o[4]}]
set_property PACKAGE_PIN J4 [get_ports {GPIO_0_tri_o[5]}]
set_property PACKAGE_PIN H4 [get_ports {GPIO_0_tri_o[6]}]
set_property PACKAGE_PIN J3 [get_ports {GPIO_0_tri_o[7]}]
set_property PACKAGE_PIN J2 [get_ports {GPIO_0_tri_o[8]}]
set_property PACKAGE_PIN K2 [get_ports {GPIO_0_tri_o[9]}]
set_property PACKAGE_PIN K1 [get_ports {GPIO_0_tri_o[10]}]
set_property PACKAGE_PIN H6 [get_ports {GPIO_0_tri_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[0]}]
set_property PACKAGE_PIN H14 [get_ports {MII_txd[0]}]
set_property PACKAGE_PIN J14 [get_ports {MII_txd[1]}]
set_property PACKAGE_PIN J13 [get_ports {MII_txd[2]}]
set_property PACKAGE_PIN H17 [get_ports {MII_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MII_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MII_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MII_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MII_txd[0]}]
set_property PACKAGE_PIN F16 [get_ports mdc]
set_property PACKAGE_PIN K13 [get_ports mdio]
set_property PACKAGE_PIN H15 [get_ports MII_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio]
set_property IOSTANDARD LVCMOS33 [get_ports MII_tx_en]

set_property PACKAGE_PIN G18 [get_ports clk25]
set_property IOSTANDARD LVCMOS33 [get_ports clk25]

set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports {tx_mirror[0]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {tx_mirror[1]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {tx_mirror[2]}]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports {tx_mirror[3]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {tx_mirror[4]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {tx_mirror[5]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {tx_mirror[6]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {tx_mirror[7]}]

set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {rx_mirror[0]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {rx_mirror[1]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {rx_mirror[2]}]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {rx_mirror[3]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {rx_mirror[4]}]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {rx_mirror[5]}]
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {rx_mirror[6]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {rx_mirror[7]}]


create_generated_clock -name clkout -source [get_pins rocketMac_i/clk] -divide_by 2 [get_pins rocketMac_i/clk_wiz_0/clk_out1]

set_false_path -from [get_clocks clkout] -to [get_clocks mrx_clk]
set_false_path -from [get_clocks clkout] -to [get_clocks mtx_clk]


set_property PULLUP true [get_ports mdio]

set_property MARK_DEBUG false [get_nets rocketMac_i/FPGATop_0/inst/i_rocketChip/mdioCtrl/mdc_reg_0]
set_property MARK_DEBUG true [get_nets {rocketMac_i/FPGATop_0/inst/tx_mirror[6]}]
set_property MARK_DEBUG true [get_nets rocketMac_i/FPGATop_0/inst/T0]
set_property MARK_DEBUG true [get_nets {rocketMac_i/FPGATop_0/inst/rx_mirror[0]}]

connect_debug_port u_ila_0/probe0 [get_nets [list {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac/gmiiTx_AxisRx/stateCurr[0]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/stateCurr[0]} {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/stateCurr[1]} {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/stateCurr[2]}]]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list rocketMac_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {rocketMac_i/FPGATop_0/inst/rx_mirror[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {rocketMac_i/FPGATop_0/inst/tx_mirror[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_rx_rxd[0]} {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_rx_rxd[1]} {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_rx_rxd[2]} {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_rx_rxd[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_tx_txd[0]} {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_tx_txd[1]} {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_tx_txd[2]} {rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_tx_txd[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_tclk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_tx_tx_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list rocketMac_i/FPGATop_0/inst/T0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_rclk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list rocketMac_i/FPGATop_0/inst/i_rocketChip/mac/mac_io_gmii_rx_rx_dv]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
